export const UPDATE_PLAYERS = 'UPDATE_PLAYERS';
export const SAVE_GAME_INFO = 'SAVE_GAME_INFO';
export const CREATING_GAME = 'CREATING_GAME';
export const CLEAR_CREATING_GAME = 'CLEAR_CREATING_GAME';
export const CLEAR_GAME = 'CLEAR_GAME';
